socket_client:
	gcc -g SocketClient/socket_client.c -o SocketClient/socket_client

socket_server:
	gcc -g SocketServer/socket_server.c -o SocketServer/socket_server

clean:
	rm socket_client socket_server